// Build-time SVG pipeline: reads the gold KickoffHQ SVGs, strips xml/doctype
// prologs, replaces the main gold #F5A302 with currentColor, and writes
// lib/svgs.ts (committed). All other fills are left untouched.
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const here = dirname(fileURLToPath(import.meta.url));
const SRC_DIR = "/home/vincerhodes/dev/kickoffhq/planning/design/svg";
const OUT = join(here, "..", "lib", "svgs.ts");

const files = [
  ["faviconSvg", "kickoff-favicon-gold.svg"],
  ["logoSvg", "kickoff-logo-gold.svg"],
  ["logoWideSvg", "kickoff-logo-wide-gold.svg"],
  ["logoHqSvg", "kickoff-logo-gold-big-hq.svg"],
  ["logoWideHqSvg", "kickoff-logo-wide-gold-big-hq.svg"],
];

function prepare(svg) {
  const stripped = svg
    .split("\n")
    .filter((line) => !line.trimStart().startsWith("<?xml") && !line.trimStart().startsWith("<!DOCTYPE"))
    .join("\n")
    .trim();
  return stripped.replace(/#F5A302/gi, "currentColor");
}

const parts = [
  "// Generated by scripts/prepare-svgs.mjs — do not edit by hand.",
  "// The main gold (#F5A302) has been replaced with currentColor; recolour via CSS color.",
  "",
];
for (const [name, file] of files) {
  const raw = readFileSync(join(SRC_DIR, file), "utf8");
  const prepped = prepare(raw);
  const count = (prepped.match(/currentColor/g) || []).length;
  console.log(`${file}: ${count} currentColor replacement(s)`);
  parts.push(`export const ${name} = ${JSON.stringify(prepped)};`, "");
}

writeFileSync(OUT, parts.join("\n"));
console.log(`wrote ${OUT}`);
